### ISSUE TITLE
BUG: getting errors while running code

### ISSUE THREAD

**Issue by mohmmad47** [pozitronik/sinner#82]
**Describe the bug**
when i try to run a `python3 sin.py` i get errors

Traceback (most recent call last):
  File "/Users/tastedrecipes/Movies/sinner/sin.py", line 7, in <module>
    from sinner.Benchmark import Benchmark
  File "/Users/tastedrecipes/Movies/sinner/sinner/Benchmark.py", line 12, in <module>
    from sinner.BatchProcessingCore import BatchProcessingCore
  File "/Users/tastedrecipes/Movies/sinner/sinner/BatchProcessingCore.py", line 11, in <module>
    from sinner.State import State
  File "/Users/tastedrecipes/Movies/sinner/sinner/State.py", line 6, in <module>
    from sinner.Status import Status, Mood
  File "/Users/tastedrecipes/Movies/sinner/sinner/Status.py", line 8, in <module>
    from sinner.typing import UTF8
  File "/Users/tastedrecipes/Movies/sinner/sinner/typing.py", line 10, in <module>
    NumeratedFrame = tuple[int, Frame, str | None]  # type: ignore[valid-type] #todo: check this # the result of frame extracting -> number of the frame and the frame itself and optional frame name
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Screenshots**
![Screenshot 2023-10-21 at 7 55 34 PM](https://github.com/pozitronik/sinner/assets/87911619/e00d8380-b00c-42da-b638-e6b0c4b37246)

**Sanity Check**
- [yes] I have the latest code from the github repository
- [yes] I have followed the installation guide

**Comment by pozitronik** [comment]
What version of Python do you use? It seems that the code was run with a Python version lower than 3.10. In fact, the program should check the interpreter version and display a proper error message, but these types of errors occurred before that check.

**Comment by mohmmad47** [comment]
![Screenshot 2023-10-23 at 5 20 11 PM](https://github.com/pozitronik/sinner/assets/87911619/2ae7979d-a7ba-47c0-9aba-b2935520aa2f)

**Comment by pozitronik** [comment]
You need a Python 3.10 at least to run the code.
I've fixed the warn message for this case.

**Comment by mohmmad47** [comment]
i have somehow managed to pass that error but now its showing me this error
![Screenshot 2023-10-23 at 6 49 15 PM](https://github.com/pozitronik/sinner/assets/87911619/24fa0ce1-288f-4468-90ff-5e340cea3b60)

**Comment by pozitronik** [comment]
> i have somehow managed to pass that error but now its showing me this error ![Screenshot 2023-10-23 at 6 49 15 PM](https://user-images.githubusercontent.com/87911619/277349739-24fa0ce1-288f-4468-90ff-5e340cea3b60.png)

You need to properly install all modules from the `requrements*.txt` file for your platform, as documented [here](https://github.com/pozitronik/sinner#how-do-i-install-it)
You can check installed modules via `pip list` command. If `onnxruntime` is in the output, it may be that pip installed the modules for some other Python interpreter (this can happen if you have different Python versions installed at the same time).
If you can't figure it out, feel free to create a new ticket, and we will try to resolve it together.
