### ISSUE TITLE
BUG: getting errors on start

### ISSUE THREAD

**Issue by mohmmad47** [pozitronik/sinner#84]
**Describe the bug**
when i give proper commmand it gives errors 

**Screenshots**
![Screenshot 2023-10-24 at 10 50 22 AM](https://github.com/pozitronik/sinner/assets/87911619/df1359eb-b016-481d-88dc-f8e99dd3acce)

**Sanity Check**
- [Yes] I have the latest code from the github repository
- [Yes] I have followed the installation guide

**Comment by mohmmad47** [comment]
what should i do @pozitronik?

**Comment by pozitronik** [comment]
> what should i do @pozitronik?

This issue occurs because ~ is used as a home path, but it is not expanded to a real path in the code. I'm already working on it, so please be patient. Alternatively, you can try running the program with expanded paths.

**Comment by pozitronik** [comment]
Should be fixed, please check.

**Comment by mohmmad47** [comment]
done bro Thank you :)
